### ISSUE TITLE
BF lifter is untested and bitrotted

### ISSUE THREAD

**Issue by chq-matteo** [angr/angr-platforms#20]
The bf lifter does not work with angr master branch (7.8.7.1)
```
Traceback (most recent call last):
  File "lift_bf.py", line 253, in <module>
    lifter = LifterBF(irsb_, test1,len(test1) , len(test1), 0, None)
TypeError: __init__() takes exactly 3 arguments (7 given)

```
Is some special version needed?

**Comment by zardus** [comment]
@subwire, do we need to (fix it and) add it to CI?

**Comment by rhelmot** [comment]
So we already CI the angr-platforms repo but this isn't tested code because it's the `if __name__ == `__main__`:` clause on one of the module files, not any of the tests. angr-platform works with the current version of angr, just...... not that one specific blob of code. It should be migrated to the tests directory.

**Comment by zardus** [comment]
Ah, yeah, I thought it was weird if BF wasn't being CIed at all, given that the repo is. I was just too lazy to check on mobile!

Anyways, @chq-matteo, check out https://github.com/angr/angr-platforms/blob/master/tests/test_angr_bf.py for how to use the BF lifter.

What we should do is probably just remove that clause from lift_bf.py

**Comment by chq-matteo** [comment]
Thank you @zardus, my understanding is that [test_angr_bf.py](https://github.com/angr/angr-platforms/blob/master/tests/test_angr_bf.py) works because it doesn't use [lift_bf.py](https://github.com/angr/angr-platforms/blob/master/angr_platforms/bf/lift_bf.py).

It relies on [engine_bf.py](https://github.com/angr/angr-platforms/blob/master/angr_platforms/bf/engine_bf.py) which does not lift the code with Gymrat.

I am interested in lift_bf.py because I like the idea of a lifter helper

**Comment by rhelmot** [comment]
So there is a test_lifter_bf.py but it looks like it doesn't actually test the lifter, I stuck some breakpoints in the lifter code and none of them triggered when I ran it. I'm really sorry for putting you through this, apparently our bf lifter is 100% untested.

@subwire please come fix your code

In the meantime, maybe look at the msp430 lifter?

**Comment by chq-matteo** [comment]
@rhelmot ok, no worries. I understand that managing such a big project is not an easy task

**Comment by bennofs** [comment]
Isn't this the bug fixed by #15? Not sure if there are more changes that broke the code since then.

**Comment by chq-matteo** [comment]
@bennofs I've just viewed your pr, I did something similar
```python
    lifter = LifterBF(archinfo.arch_from_id('bf'), 0)
    lifter.irsb = irsb_
    lifter.data = test1
    lifter.max_bytes = len(test1)
    lifter.max_inst = len(test1)
    lifter.lift()
    lifter.irsb.pp()
```
Looking into [lifter.py#L52](https://github.com/angr/pyvex/blob/master/pyvex/lifting/lifter.py#L52) it looks like I partially reimplemented the _lift method

**Comment by chq-matteo** [comment]
The [msp430](https://github.com/angr/angr-platforms/blob/master/angr_platforms/msp430/lift_msp430.py#L16) lifter also has the same snippet of code as the bf lifter, so I am inclined to believe that there is just some missing commit to Gymrat

Maybe the __init__ method of Gymrat was supposed to call _lift under the hood?

**Comment by chq-matteo** [comment]
[SimEngineVEX lift](https://github.com/angr/angr/blob/master/angr/engines/vex/engine.py#L513) creates an IRSB which in turn uses [lifting.lift](https://github.com/angr/pyvex/blob/master/pyvex/block.py#L82)  which uses [_lift](https://github.com/angr/pyvex/blob/master/pyvex/lifting/__init__.py#L82)

Maybe your way is the intended way to use a Gymrat lifter?

**Comment by rhelmot** [comment]
`lifting.lift` is definitely supposed to be the canonical way to create an IRSB.

**Comment by rhelmot** [comment]
...or, uh, `lifting.lift` _will_ be the canonical way to create an IRSB as soon as an in-progress pull request lands. Right now the canonical way is the IRSB constructor.
