### ISSUE TITLE
Can not create new branch for pull request

### ISSUE THREAD

**Issue by stefanberg96** [angr/angr-platforms#34]
I have made a lifter for RISC-V 32 bit with multiplication and division, compact and atomic extensions to use in my masters thesis. I would like to add the resulting lifter to this repository for other people to use. However when I try to create a brahc called wip/risc-v_32bit I get the error that the permissions are denied. Could someone create the branch for me to push to?

**Comment by rhelmot** [comment]
Even if I made a branch for you, you wouldn't be able to push to it. On github, you're supposed to fork the repository, then push to your fork.

**Comment by stefanberg96** [comment]
Ah okay, sorry for this newbie question I was not aware that forked repositories could also create a pull request.
