### ISSUE TITLE
Do you have any plans to support riscv 64bit?

### ISSUE THREAD

**Issue by endarque** [angr/angr-platforms#41]
Hi.

I want to execute 'symbolic execution' with angr for riscv 64bit ELF file.

However, none of the programs support it.

So, do you have any plans to support riscv 64bit?

**Comment by rhelmot** [comment]
Sorry, we do not. None of our research objectives hinge on being able to analyze risc-v code. However, you can use the tutorial in this repository to build your own risc-v64 lifter, maybe based on the existing 32-bit lifter.

**Comment by endarque** [comment]
> Sorry, we do not. None of our research objectives hinge on being able to analyze risc-v code. However, you can use the tutorial in this repository to build your own risc-v64 lifter, maybe based on the existing 32-bit lifter.

Thank you for your comment. I try that.
