### ISSUE TITLE
No module named procedures

### ISSUE THREAD

**Issue by ikhwan12** [angr/angr-platforms#5]
Hi, I am trying your new architecture (angr-bf). I wanna feel new experience.
Unfortunately, I got an error like this :

Traceback (most recent call last):
  File "findflagsolver.py", line 5, in <module>
    from angr_bf import arch_bf, load_bf, simos_bf
  File "/home/f000/.virtualenvs/aegg/local/lib/python2.7/site-packages/angr_bf/simos_bf.py", line 2, in <module>
    from angr.procedures import SIM_PROCEDURES as P, SIM_LIBRARIES as L
ImportError: No module named procedures

There is no module named procedures. I even have updated angr to the newest version.
I don't know how to solve it. Can you explain to me how to fix this ?
Thank you.

**Comment by rhelmot** [comment]
Hello! angr is currently going through a big refactor that will culminate in a major version release. this version of the repository has been updated with the new APIs, and is as such incompatible with the version of angr currently on pip. If you want to get this working you should either install angr via the angr-dev Github repository (just a setup script to pull all the repositories from Github basically) or check out an older version of this repo from before the refactor began.

**Comment by ikhwan12** [comment]
Ow, I see. Ok, I will try it. Thank you for your answer. :+1:
