### ISSUE TITLE
MULSU instruction lifting not well typed operation error

### ISSUE THREAD

**Issue by MrAle98** [angr/angr-platforms#50]
Hello I was trying to launch CFG analysis over a risc-v binary, and I got the following error:
![image](https://user-images.githubusercontent.com/74059030/166428385-13954ea6-de9f-46e2-b90c-edf3fe850044.png)

By replacing type to int_64 in the following way (inside instrs_risc.r_instr.py) I get no more the exception:
![image](https://user-images.githubusercontent.com/74059030/166428620-76fd177e-9c66-4a49-8513-aa73a8a16e27.png)

Is it correct the fix?

**Comment by rhelmot** [comment]
Everything in this repository is contributed code, so we really don't know how to tell whether something is correct. If you can provide a patch and a new testcase to verify your new behavior in a pull request we will gladly accept it, but there's not much more we can do.

**Comment by MrAle98** [comment]
I understand, thanks for your reply.
